version: '3'
services:
  db:
    image: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j123

  backend:
    build: .
    volumes:
      - "${PWD}/backend:/home/node"
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: "npm run start"

volumes:
  backend:
