export let e_error = {
    BAD_VALIDATION: 1,
    BAD_CREDENTIALS: 2,
    NOT_FOUND: 3,
    MAIL_EXIST: 4,
    USERNAME_EXIST: 5,
    INVALID_TOKEN: 6,
    INVALID_FILE: 7,
    CANNOT_LIKE: 8,
    CANNOT_UNLIKE: 9,
    CANNOT_BLOCK: 10,
    ROOM_NOT_CREATED: 11,
    ROOM_NOT_DELETED: 12,
    MSG_NOT_SENT: 13,
    BLOCKED_BY_USER: 14
}